import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'
import { RootProviders } from './providers'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <RootProviders>
      <html lang="pt-BR" suppressHydrationWarning>
        <body className={`${inter.variable} antialiased space-y-10`}>
          <Header />
          <main className="w-full pt-[116px]">{children}</main>
          <Footer />
        </body>
      </html>
    </RootProviders>
  )
}
